### ISSUE TITLE
Can't add more than one SBB device

### ISSUE THREAD

**Issue by ebotheblue1** [gslender/com.gslender.sbb#1]
I have four identical SBB fans, each has it's own IP and token.  I added the first and it works great but when I tray and add a second (using it unique IP and token) I get an error saying "duplicate device data" and the fan never adds.

**Comment by gslender** [comment]
Thanks for reporting this. I think I've fixed it and pushed out v1.0.14 as an update that should fix this. I don't have multiple devices so couldn't test for this scenario. You may need to delete the first/original fan too!

**Comment by gslender** [comment]
fixed in v1.0.14
